# Jenkins Master
jenkins:
  image: blacklabelops/jenkins
  container_name: jenkins
  ports:
   - "8080:8080"
   - "50000"
  expose:
   - "8080"
  volumes_from:
    - volumes
  env_file:
    - jenkins-master-security.env
  labels:
    com.blacklabelops.description: "Jenkins Continuous Integration System"
    com.blacklabelops.service: "jenkins-master"
# Global volume container
volumes:
  image: blacklabelops/centos
  container_name: jenkins_data
  volumes:
    # Logging volumes
    - /var/log
    # Jenkins volume
    - /jenkins
  command: chown -R 1000:1000 /var/log /jenkins
# Jenkins Slave
slave:
  image: blacklabelops/swarm-jdk8
  name: "slave"
  links:
    - jenkins:jenkins
  env_file:
    - jenkins-slave-security.env
  labels:
    com.blacklabelops.description: "Jenkins Swarm JDK-8 Slave"
    com.blacklabelops.service: "slave"
    com.blacklabelops.applications: "java maven gradle"
