# nginx reverse proxy
nginx:
  image: jwilder/nginx-proxy
  container_name: nginx-proxy
  ports:
    - "80:80"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
  links:
    - app

app:
  build: .
  name: "app"
  container_name: app
  ports:
    - "8000:8000"
